services:
  transactionsdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123"
    ports:
      - "1433:1433"
    volumes:
      - mssql_transactions:/var/opt/mssql

  paymentsdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123"
    ports:
      - "1434:1433"
    volumes:
      - mssql_payments:/var/opt/mssql

  messagebroker:
    image: rabbitmq:3-management-alpine

  payments.api:
    image: ${DOCKER_REGISTRY-}paymentsapi
    build:
      context: .
      dockerfile: src/Services/Payments/Payments.API/Dockerfile

  transactions.api:
    image: ${DOCKER_REGISTRY-}transactionsapi
    build:
      context: .
      dockerfile: src/Services/Transactions/Transactions.API/Dockerfile

volumes:
  mssql_transactions:
  mssql_payments:

