services:
  transactionsdb:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    restart: always
    ports:
      - "1433:1433"
    volumes:
     - mssql_transactions:/var/opt/mssql

  paymentsdb:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    restart: always
    ports:
      - "1435:1433"
    volumes:
      - mssql_payments:/var/opt/mssql

  messagebroker:
    container_name: messagebroker
    hostname: payment-platform-messagebroker
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
